---
name: Google-Spreadsheet-Agent
version: 0.01
author:
  - 'Darin London <darin.london@duke.edu>'
abstract: A Distributed Agent System using Google Spreadsheets
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  IO::CaptureOutput: '>= 1.1101'
  Moose: '>= 0.79'
  Net::Google::Spreadsheets: '>= 0.04'
  Net::SMTP::TLS: '>= 0.12'
  YAML::Any: '>= 0.67'
build_requires:
  Test::More: 0
provides:
  Google::Spreadsheet::Agent:
    file: lib/Google/Spreadsheet/Agent.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
